// Initial data used ONLY the first time the database is empty. After that,
// everything lives in MongoDB and is managed through the CMS.

const categories = [
  { id: "burgers", sortOrder: 1, labelFr: "Burgers", labelEn: "Burgers", labelAr: "برغر" },
  { id: "pizza", sortOrder: 2, labelFr: "Pizzas", labelEn: "Pizza", labelAr: "بيتزا" },
  { id: "chicken", sortOrder: 3, labelFr: "Poulet", labelEn: "Chicken", labelAr: "دجاج" },
  { id: "sides", sortOrder: 4, labelFr: "Accompagnements", labelEn: "Sides", labelAr: "أطباق جانبية" },
  { id: "drinks", sortOrder: 5, labelFr: "Boissons", labelEn: "Drinks", labelAr: "مشروبات" },
  { id: "desserts", sortOrder: 6, labelFr: "Desserts", labelEn: "Desserts", labelAr: "حلويات" }
];

const menuItems = [
  { id:"classic-smash-burger", categoryId:"burgers", sortOrder:1, price:52, discountPrice:null, image:"images/burgers/classic-smash-burger.jpg", featured:1, recommended:1, available:1,
    nameFr:"Classic Smash Burger", nameEn:"Classic Smash Burger", nameAr:"كلاسيك سماش برغر",
    descFr:"Double steak smashé, cheddar, sauce maison, pain brioché toasté.",
    descEn:"Double smashed beef patty, cheddar, house sauce, toasted brioche bun.",
    descAr:"قطعتان من اللحم المطحون المشوي، جبن شيدر، صلصة خاصة، خبز بريوش محمّص." },
  { id:"ember-cheese-burger", categoryId:"burgers", sortOrder:2, price:48, discountPrice:null, image:"images/burgers/ember-cheese-burger.jpg", featured:0, recommended:1, available:1,
    nameFr:"Ember Cheese Burger", nameEn:"Ember Cheese Burger", nameAr:"إمبر تشيز برغر",
    descFr:"Cheddar fondu, oignons caramélisés, sauce ember fumée, laitue croquante.",
    descEn:"Melted cheddar, caramelised onions, smoky ember sauce, crisp lettuce.",
    descAr:"جبن شيدر ذائب، بصل مكرمل، صلصة إمبر المدخنة، خس مقرمش." },
  { id:"spicy-burger-combo", categoryId:"burgers", sortOrder:3, price:65, discountPrice:52, image:"images/burgers/spicy-burger-combo.jpg", featured:1, recommended:0, available:1,
    nameFr:"Spicy Burger Combo", nameEn:"Spicy Burger Combo", nameAr:"سبايسي برغر كومبو",
    descFr:"Jalapeños croustillants, pepper-jack, mayo chipotle, servi avec frites et boisson.",
    descEn:"Crispy jalapeños, pepper-jack, chipotle mayo, served with fries and a drink.",
    descAr:"فلفل هالبينو مقرمش، جبن بيبر جاك، مايونيز تشيبوتلي، يُقدَّم مع البطاطس ومشروب." },
  { id:"double-smash-burger", categoryId:"burgers", sortOrder:4, price:70, discountPrice:null, image:"images/burgers/double-smash-burger.jpg", featured:0, recommended:0, available:1,
    nameFr:"Double Smash Burger", nameEn:"Double Smash Burger", nameAr:"دبل سماش برغر",
    descFr:"Deux steaks épais, triple cheddar, cornichons, glaçage barbecue fumé.",
    descEn:"Two extra-thick patties, triple cheddar, pickles, smoked BBQ glaze.",
    descAr:"قطعتان سميكتان من اللحم، جبن شيدر ثلاثي، مخلل، صلصة باربكيو مدخنة." },
  { id:"margherita-pizza", categoryId:"pizza", sortOrder:1, price:62, discountPrice:null, image:"images/pizza/margherita-pizza.jpg", featured:0, recommended:1, available:1,
    nameFr:"Pizza Margherita", nameEn:"Margherita Pizza", nameAr:"بيتزا مارغريتا",
    descFr:"Tomate San Marzano, mozzarella fior di latte, basilic frais, huile d'olive.",
    descEn:"San Marzano tomato, fior di latte mozzarella, fresh basil, olive oil.",
    descAr:"طماطم سان مارزانو، جبن موزاريلا طازجة، ريحان طازج، زيت زيتون." },
  { id:"pepperoni-pizza", categoryId:"pizza", sortOrder:2, price:72, discountPrice:null, image:"images/pizza/pepperoni-pizza.jpg", featured:0, recommended:0, available:1,
    nameFr:"Pizza Pepperoni", nameEn:"Pepperoni Pizza", nameAr:"بيتزا ببروني",
    descFr:"Double pepperoni, mozzarella, base tomate, origan, filet d'huile pimentée.",
    descEn:"Double pepperoni, mozzarella, tomato base, oregano, chili oil drizzle.",
    descAr:"طبقة مزدوجة من الببروني، جبن موزاريلا، صلصة طماطم، أوريغانو، زيت حار." },
  { id:"bbq-chicken-pizza", categoryId:"pizza", sortOrder:3, price:78, discountPrice:null, image:null, featured:0, recommended:0, available:1,
    nameFr:"Pizza Poulet BBQ", nameEn:"BBQ Chicken Pizza", nameAr:"بيتزا الدجاج بالباربكيو",
    descFr:"Poulet grillé, sauce barbecue fumée, oignon rouge, mozzarella, coriandre.",
    descEn:"Grilled chicken, smoked BBQ sauce, red onion, mozzarella, coriander.",
    descAr:"دجاج مشوي، صلصة باربكيو مدخنة، بصل أحمر، جبن موزاريلا، كزبرة." },
  { id:"crispy-chicken-tenders", categoryId:"chicken", sortOrder:1, price:55, discountPrice:null, image:"images/chicken/crispy-chicken-tenders.jpg", featured:1, recommended:0, available:1,
    nameFr:"Tenders de Poulet Croustillants", nameEn:"Crispy Chicken Tenders", nameAr:"تندرز دجاج مقرمش",
    descFr:"Tenders marinés au babeurre, panure croustillante, sauce maison au choix.",
    descEn:"Buttermilk-marinated tenders, crunchy coating, choice of house dip.",
    descAr:"قطع دجاج متبلة باللبن، طبقة مقرمشة، مع صلصة منزلية حسب الاختيار." },
  { id:"spicy-fried-chicken", categoryId:"chicken", sortOrder:2, price:60, discountPrice:48, image:"images/chicken/spicy-fried-chicken.jpg", featured:0, recommended:0, available:1,
    nameFr:"Poulet Frit Épicé", nameEn:"Spicy Fried Chicken", nameAr:"دجاج مقلي حار",
    descFr:"Cuisse de poulet panée à la main, glaçage au piment, coleslaw, pain brioché.",
    descEn:"Hand-breaded chicken thigh, cayenne glaze, pickled slaw, brioche bun.",
    descAr:"فخذ دجاج مقرمش محضّر يدويًا، صلصة حارة، سلطة ملفوف مخللة، خبز بريوش." },
  { id:"grilled-chicken-wrap", categoryId:"chicken", sortOrder:3, price:42, discountPrice:null, image:null, featured:0, recommended:1, available:1,
    nameFr:"Wrap Poulet Grillé", nameEn:"Grilled Chicken Wrap", nameAr:"راب دجاج مشوي",
    descFr:"Blanc de poulet grillé, sauce yaourt à l'ail, crudités, galette moelleuse.",
    descEn:"Grilled chicken breast, garlic yogurt sauce, crisp greens, soft flatbread.",
    descAr:"صدر دجاج مشوي، صلصة زبادي بالثوم، خضار طازجة، خبز رقيق طري." },
  { id:"loaded-fries", categoryId:"sides", sortOrder:1, price:32, discountPrice:null, image:"images/sides/loaded-fries.jpg", featured:0, recommended:0, available:1,
    nameFr:"Frites Loaded Ember", nameEn:"Loaded Ember Fries", nameAr:"بطاطس إمبر المحمّلة",
    descFr:"Frites croustillantes, cheddar fondu, éclats de bœuf fumé, sauce ember.",
    descEn:"Crispy fries, melted cheddar, smoked beef bits, ember sauce drizzle.",
    descAr:"بطاطس مقرمشة، جبن شيدر ذائب، قطع لحم بقري مدخن، صلصة إمبر." },
  { id:"onion-rings", categoryId:"sides", sortOrder:2, price:28, discountPrice:null, image:null, featured:0, recommended:0, available:1,
    nameFr:"Onion Rings Croustillants", nameEn:"Crispy Onion Rings", nameAr:"حلقات بصل مقرمشة",
    descFr:"Rondelles d'oignon panées dorées, servies avec sauce fumée.",
    descEn:"Golden battered onion rings, served with a smoky dip sauce.",
    descAr:"حلقات بصل مقلية ذهبية، تُقدَّم مع صلصة مدخنة." },
  { id:"fresh-lemonade", categoryId:"drinks", sortOrder:1, price:18, discountPrice:null, image:"images/drinks/fresh-lemonade.jpg", featured:0, recommended:0, available:1,
    nameFr:"Citronnade Fraîche", nameEn:"Fresh Lemonade", nameAr:"ليموناضة طازجة",
    descFr:"Citrons pressés à la main, feuilles de menthe, légèrement pétillante, bien fraîche.",
    descEn:"Hand-squeezed lemons, mint leaves, lightly sparkling, served ice-cold.",
    descAr:"ليمون معصور يدويًا، أوراق نعناع، فوارة قليلاً، تُقدَّم مثلجة." },
  { id:"iced-cola", categoryId:"drinks", sortOrder:2, price:15, discountPrice:null, image:"images/drinks/iced-cola.jpg", featured:0, recommended:0, available:1,
    nameFr:"Cola Glacé", nameEn:"Iced Cola", nameAr:"كولا مثلجة",
    descFr:"Cola classique, servi bien frais sur glace pilée.",
    descEn:"Classic cola, served ice-cold over crushed ice.",
    descAr:"كولا كلاسيكية، تُقدَّم باردة جدًا مع ثلج مجروش." },
  { id:"chocolate-lava-cake", categoryId:"desserts", sortOrder:1, price:38, discountPrice:null, image:"images/desserts/chocolate-lava-cake.jpg", featured:1, recommended:1, available:1,
    nameFr:"Fondant au Chocolat", nameEn:"Chocolate Lava Cake", nameAr:"كيك الشوكولاتة الذائبة",
    descFr:"Gâteau chaud au chocolat noir, cœur coulant, boule de glace vanille.",
    descEn:"Warm dark chocolate cake, molten centre, scoop of vanilla ice cream.",
    descAr:"كيك دافئ بالشوكولاتة الداكنة، بقلب سائل، مع كرة آيس كريم بالفانيليا." },
  { id:"caramel-cheesecake", categoryId:"desserts", sortOrder:2, price:36, discountPrice:null, image:"images/desserts/caramel-cheesecake.jpg", featured:0, recommended:0, available:0,
    nameFr:"Cheesecake Caramel Beurre Salé", nameEn:"Salted Caramel Cheesecake", nameAr:"تشيز كيك الكراميل المملح",
    descFr:"Cheesecake crémeux cuit au four, caramel au beurre salé, croûte biscuitée.",
    descEn:"Creamy baked cheesecake, salted caramel drizzle, biscuit crust.",
    descAr:"تشيز كيك كريمي مخبوز، صلصة كراميل مملح، قاعدة بسكويت." }
];

// Fields NOT exposed as editable in the CMS (branding/theme) still live here so the
// public page has a single source of truth to fetch from, but the admin UI only
// exposes the "restaurant info" subset (hours, address, phone, WhatsApp, socials).
const restaurantInfo = {
  name: "Ember Table",
  logoInitials: "ET",
  currency: "MAD",
  whatsappNumber: "212600000000",
  defaultLanguage: "fr",
  defaultTheme: "dark",
  animationIntensity: "subtle",
  heroImage: "images/hero/hero-signature-dish.jpg",
  openingHoursFr: "12h00–23h30",
  openingHoursEn: "12:00–23:30",
  openingHoursAr: "12:00–23:30",
  addressFr: "12 Avenue des Saveurs, Casablanca",
  addressEn: "12 Avenue des Saveurs, Casablanca",
  addressAr: "12 شارع النكهات، الدار البيضاء",
  phone: "+212 6 00 00 00 00",
  phoneHref: "tel:+212600000000",
  socialInstagram: "#",
  socialFacebook: "#",
  socialTiktok: "#"
};

module.exports = { categories, menuItems, restaurantInfo };
